site_name: FluentScheduler
site_url: http://fluentscheduler.github.io
site_description: Automated job scheduler with fluent interface.

plugins: []

nav:
  - Home: index.md
  - Creating schedules: creating-schedules.md
  - Starting, stopping and resetting: starting-stopping-and-resetting.md
  - Changing the scheduling: changing-the-scheduling.md
  - Listening for events: listening-for-events.md
  - Grouping schedules: grouping-schedules.md
  - Reentrancy: reentrancy.md
  - Cron expressions: cron-expressions.md
  - Daylight savings: daylight-savings.md
  - UTC: utc.md
  - More examples: more-examples.md
  - Contributing: contributing.md

theme:
  name: readthedocs
  custom_dir: docs/custom